### PR TITLE
150 dropdown menu does not work with the base theme alone

### PR DESCRIPTION
**Pull request by zipymonkey**
… with class.

There should be no visual change on this.  Porting https://github.com/psu-libraries/psul-web/blob/main/web/themes/custom/psul_theme/templates/navigation/menu--main.html.twig into the base theme.  Adjusted javascript to handle a class or an id for the main menu.

This should probably be included in component.

### CODE REVIEW

**Comment by XSPSUGitHub** [comment]
@zipymonkey, when i test this locally, clicking on the top main menu item doesn't display a list of the pages. is this the expected behavior?

**Comment by zipymonkey** [comment]
The dropdowns _should_ work.  I thought it was working locally for me but I'll double check.

**Comment by zipymonkey** [comment]
@XSPSUGitHub It is working for me with both the psul_theme (subtheme) and the psulib_base theme enabled.  Did you rebuild the theme and clear the cache?

## PSUL Theme
https://github.com/user-attachments/assets/5cab3094-9b21-4012-8345-6603b9d2f0d4


## PSULIB BASE Theme
https://github.com/user-attachments/assets/cfa9b1d1-33e7-47f6-bbfe-20d9390fbd43

**Comment by XSPSUGitHub** [comment]
@zipymonkey, i tested again and it's working for me now. I did rebuild cache both times. i was on `drupal-site-template` for testing this. maybe the new changes in `drupal-site-template` made a difference?

**Review by XSPSUGitHub — APPROVED** [review]
works for me

**Pull request merged**
